name: personal_finance
description: A personal finance app to manage expenses and earnings, organising them into groups and viewing overall transactions

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Service locator
  get_it: ^7.6.0
  # Bloc for state management
  flutter_bloc: ^8.1.3
  # Value equality
  equatable: ^2.0.5
  # Functional programming
  dartz: ^0.10.1
  # Storage
  floor: ^1.4.2
  sqflite: ^2.3.0
  # Dates + languages
  intl: ^0.18.1
  # Charts
  fl_chart: ^0.63.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  floor_generator: ^1.4.2
  build_runner: ^2.4.6

  # rules and activating additional ones.
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
